from fastapi import HTTPException

from database import Session
from models import Categories, Accounts
from schemas import CreateCategory
from sqlalchemy.exc import IntegrityError
from fastapi import HTTPException


def create_category(email:str,category: CreateCategory):
    with Session() as session:
        try:
            account = session.query(Accounts).filter(Accounts.email == email).first()
            if not account:
                raise HTTPException(status_code=404, detail="Account not found")
            new_category = Categories(
                name=category.category_name,
                monthly_budget=category.monthly_budget,
                account_id=account.id
            )
            check = session.query(Categories).filter(Categories.name == category.category_name).filter(Categories.account_id == account.id).first()
            if check:
                raise HTTPException(status_code=409, detail="Category already exists")
            session.add(new_category)
            session.commit()
            # Refreshing loads the ID generated by the DB
            session.refresh(new_category)
            return new_category


        except Exception as e:
            session.rollback()
            print(e)
            raise HTTPException(status_code=500, detail="An internal server error occurred.")